# Generated by Django 5.2.5 on 2025-09-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='photos/AND_GATE.png', null=True, upload_to='photos/')),
                ('place', models.TextField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
